default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kouken_report_app_development
  username: nakam


test:
  <<: *default
  database: kouken_report_app_test
  username: nakam


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
